import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zaijoy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 

  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="../public/images/logo.png"/>
      </head>
      <body className={inter.className}>
        <div className="relative">
          <Navbar />
        </div>
       <div className=" w-screen">
        {children}
       </div>
        <Footer />
      </body>
    </html>
  );
}
