export {default as Welcome } from './about/Welcome'
export {default as WhyChooseUs} from './about/WhyChooseUs'
export {default as Awards } from './about/Awards'
export {default as Team} from './about/Team'
export {default as Faqs } from './Faqs'
export {default as Branch} from './about/Branch'
export {default as Embark} from './Embark'
export {default as Gallery} from './about/Galary'