export {default as Welcome } from './about/Welcome'
export {default as WhyChooseUs} from './about/WhyChooseUs'
export {default as Awards } from './about/Awards'
export {default as Team} from './about/Team'
export {default as Faqs } from './Faqs'
export {default as Branch} from './about/Branch'
export {default as Embark} from './Embark'
export {default as Gallery} from './about/Galary'
export {default as Adventure} from './Adventure'
export {default as Form} from './Form'
export {default as Services} from './Services'
export {default as Teams} from './Teams'
export {default as Pricing} from './Pricing'
export {default as Features} from './Home/Features'
export {default as Dedicated} from './Home/Dedicated'
export {default as Enhance} from './Enhance'